[package]
name = "aoc"
version = "0.1.0"
authors = ["Mitch Souders <mitch.souders@gmail.com>"]
edition = "2018"

[dependencies]
itertools = ""
serde_scan = ""
serde = { version="", features = ["derive"]}
regex = "1"
chrono = "0.4"